apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-agent
spec:
  selector:
    matchLabels:
      app: ado-agent
  template:
    metadata:
      labels:
        app: ado-agent
    spec:
      initContainers:
        - name: setup
          image: python:3-alpine
          command:
            - /bin/sh
            - -c
            - |
              apk update && \
              apk upgrade && \
              apk add bash curl gcc git icu-libs jq musl-dev python3-dev libffi-dev openssl-dev cargo make
              pip install --upgrade pip
              pip install azure-cli
              mkdir -p /azp/_work
          volumeMounts:
            - name: work
              mountPath: /azp/_work
      containers:
        - name: agent
          image: python:3-alpine
          command:
            - /scripts/start.sh
          env:
            - name: TARGETARCH
              value: linux-musl-x64
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: ado-agent-secret
                  key: AZP_URL
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ado-agent-secret
                  key: AZP_TOKEN
            - name: AZP_POOL
              valueFrom:
                secretKeyRef:
                  name: ado-agent-secret
                  key: AZP_POOL
            - name: AZP_WORK
              value: /azp/_work
          volumeMounts:
            - name: startup-script
              mountPath: /scripts
            - name: work
              mountPath: /azp/_work
      volumes:
        - name: startup-script
          configMap:
            name: ado-agent-startup
            defaultMode: 0755
        - name: work
          emptyDir: {}
