apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - trigger-auth.yaml
  - scaled-object.yaml

commonLabels:
  app: ado-agent
  managed-by: kustomize
