apiVersion: v1
kind: Service
metadata:
  name: informix
spec:
  type: ClusterIP
  ports:
    - name: sqlhosts
      port: 9088
      targetPort: 9088
      protocol: TCP
    - name: drda
      port: 9089
      targetPort: 9089
      protocol: TCP
  selector:
    app: informix
