apiVersion: apps/v1
kind: Deployment
metadata:
  name: azp-agent
spec:
  selector:
    matchLabels:
      app: azp-agent
  template:
    metadata:
      labels:
        app: azp-agent
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: agent
          image: ghcr.io/jctekdev/azp-agent-alpine:latest
          imagePullPolicy: Always
          env:
            - name: TARGETARCH
              value: linux-musl-x64
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: azp-agent-secret
                  key: AZP_URL
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azp-agent-secret
                  key: AZP_TOKEN
            - name: AZP_POOL
              valueFrom:
                secretKeyRef:
                  name: azp-agent-secret
                  key: AZP_POOL
            - name: AZP_WORK
              value: /azp/_work
          volumeMounts:
            - name: work
              mountPath: /azp/_work
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
      volumes:
        - name: work
          emptyDir: {}
