apiVersion: apps/v1
kind: Deployment
metadata:
  name: azp-agent
spec:
  selector:
    matchLabels:
      app: azp-agent
  template:
    metadata:
      labels:
        app: azp-agent
    spec:
      containers:
        - name: agent
          image: ghcr.io/jctekdev/azp-agent:linux
          env:
            - name: TARGETARCH
              value: linux-musl-x64
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: azp-agent-secret
                  key: AZP_URL
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azp-agent-secret
                  key: AZP_TOKEN
            - name: AZP_POOL
              valueFrom:
                secretKeyRef:
                  name: azp-agent-secret
                  key: AZP_POOL
            - name: AZP_WORK
              value: /azp/_work
          volumeMounts:
            - name: work
              mountPath: /azp/_work
      volumes:
        - name: work
          emptyDir: {}
