apiVersion: apps/v1
kind: Deployment
metadata:
  name: azp-agent
spec:
  selector:
    matchLabels:
      app: azp-agent
  template:
    metadata:
      labels:
        app: azp-agent
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: agent
          image: ghcr.io/jctekdev/azp-agent-alpine:latest
          env:
            - name: TARGETARCH
              value: linux-musl-x64
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: azp-agent-secret
                  key: AZP_URL
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azp-agent-secret
                  key: AZP_TOKEN
            - name: AZP_POOL
              valueFrom:
                secretKeyRef:
                  name: azp-agent-secret
                  key: AZP_POOL
            - name: AZP_WORK
              value: /azp/_work
          volumeMounts:
            - name: work
              mountPath: /azp/_work
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
      volumes:
        - name: work
          emptyDir: {}
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
